import './AddNewTodo.scss';
import { TodoType } from '@/types/todoType';
import { createTodo } from '@/api/service';
import CrossIcon from '../Icons/CrossIcon';

export default function AddNewTodo() {
  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const formData = new FormData(event.currentTarget);
    const titleTodo = formData.get('title-input');
    const contentTodo = formData.get('title-content');

    if (!titleTodo) return;

    const newTodo: Omit<TodoType, 'id'> = {
      //id generated by the server
      title: titleTodo.toString(),
      content: contentTodo ? contentTodo.toString() : '',
      isCompleted: false,
      completedAt: null,
      createdAt: new Date(),
    };

    createTodo(newTodo);

    event.currentTarget.reset();
  };

  return (
    <form className='AddNewTodo' onSubmit={handleSubmit}>
      <div className='inputs'>
        <input
          name='title-input'
          type='text'
          placeholder='Title*'
          maxLength={80}
          autoComplete='off'
          required
        />
        <textarea
          name='title-content'
          rows={3}
          maxLength={200}
          placeholder='Description...'
        />
      </div>
      <button type='submit'>
        <CrossIcon className='CrossIcon' />
      </button>
    </form>
  );
}
